#!/usr/bin/env python3
"""Score a project's answers against the IMP five-dimension questionnaire
and render a Markdown impact report.

Usage:
    python evaluate.py answers.json [--out report.md]

See reference/imp-five-dimensions.md for the scoring model, and
reference/answers.example.json for the expected input shape.
"""
import argparse
import json
import sys
from pathlib import Path

RISK_KEYS = [
    "evidence_risk",
    "external_risk",
    "stakeholder_participation_risk",
    "drop_off_risk",
    "efficiency_risk",
    "unexpected_impact_risk",
]

COUNTERFACTUAL_SCORES = {"none": 5, "some": 4, "much": 2, "most": 1}


def _band_scale(scale):
    if scale < 100:
        return 1
    if scale <= 1000:
        return 3
    return 5


def _band_duration(years):
    if years < 1:
        return 1
    if years <= 3:
        return 3
    return 5


def score(answers):
    what_score = answers["outcome_importance"]
    who_score = answers["stakeholder_underserved"]

    how_much_score = (
        _band_scale(answers["scale"])
        + answers["depth"]
        + _band_duration(answers["duration_years"])
    ) / 3

    counterfactual = answers["counterfactual"]
    if counterfactual not in COUNTERFACTUAL_SCORES:
        raise ValueError(
            f"counterfactual must be one of {list(COUNTERFACTUAL_SCORES)}, got {counterfactual!r}"
        )
    contribution_score = COUNTERFACTUAL_SCORES[counterfactual]

    missing_risks = [k for k in RISK_KEYS if k not in answers]
    if missing_risks:
        raise ValueError(f"missing risk scores: {missing_risks}")
    risk_score = sum(answers[k] for k in RISK_KEYS) / len(RISK_KEYS)

    impact_score = (
        what_score + who_score + how_much_score + contribution_score
    ) / 4 - max(0, risk_score - 3) * 0.5
    impact_score = max(1.0, min(5.0, impact_score))

    valence = answers.get("outcome_valence", "positive")
    if valence == "negative":
        classification = "A: Act to Avoid Harm"
    elif impact_score >= 4 and contribution_score >= 4:
        classification = "C: Contribute to Solutions"
    elif impact_score >= 2.5:
        classification = "B: Benefit Stakeholders"
    else:
        classification = "Insufficient impact evidence"

    return {
        "what_score": round(what_score, 2),
        "who_score": round(who_score, 2),
        "how_much_score": round(how_much_score, 2),
        "contribution_score": round(contribution_score, 2),
        "risk_score": round(risk_score, 2),
        "impact_score": round(impact_score, 2),
        "classification": classification,
    }


def render_report(answers, result):
    lines = [
        f"# IMM Impact Report — {answers.get('project_name', 'Untitled project')}",
        "",
        f"**Classification:** {result['classification']}",
        f"**Overall impact score:** {result['impact_score']} / 5",
        "",
        "## Dimension scores",
        "",
        "| Dimension | Score (1–5) |",
        "|---|---|",
        f"| What | {result['what_score']} |",
        f"| Who | {result['who_score']} |",
        f"| How much | {result['how_much_score']} |",
        f"| Contribution | {result['contribution_score']} |",
        f"| Risk (higher = riskier) | {result['risk_score']} |",
        "",
        "## Notes",
        "",
        answers.get("notes", "_No additional notes provided._"),
        "",
        "---",
        "_Generated by RoboEvaluater — a simplified, open operationalization of the "
        "IMP five dimensions. See reference/imp-five-dimensions.md for methodology._",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("answers", type=Path, help="Path to a JSON answers file")
    parser.add_argument("--out", type=Path, help="Write report to this path instead of stdout")
    args = parser.parse_args()

    answers = json.loads(args.answers.read_text(encoding="utf-8"))
    result = score(answers)
    report = render_report(answers, result)

    if args.out:
        args.out.write_text(report, encoding="utf-8")
    else:
        print(report)


if __name__ == "__main__":
    sys.exit(main())
